[0m15:00:25.542641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1145fa8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1157aa650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1157a9f30>]}


============================== 15:00:25.544971 | 84f0cfae-fc71-40df-9b40-17cf9c687955 ==============================
[0m15:00:25.544971 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:00:25.545323 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/savana/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:01:26.551369 [debug] [MainThread]: Starter project path: /Users/savana/Desktop/BokksuV2/dbt-persona-project/venv/lib/python3.10/site-packages/dbt/include/starter_project
[0m15:01:26.555551 [info ] [MainThread]: 
Your new dbt project "dbt_persona" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:01:26.555844 [info ] [MainThread]: Setting up your profile.
[0m15:29:48.699433 [info ] [MainThread]: Profile dbt_persona written to /Users/savana/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:29:48.703577 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 1763.224, "process_in_blocks": "0", "process_kernel_time": 0.130812, "process_mem_max_rss": "123224064", "process_out_blocks": "0", "process_user_time": 0.790412}
[0m15:29:48.704223 [debug] [MainThread]: Command `dbt init` succeeded at 15:29:48.704083 after 1763.22 seconds
[0m15:29:48.704641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1145fa8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11571e2f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1157ab1c0>]}
[0m15:29:48.705055 [debug] [MainThread]: Flushing usage events
[0m15:29:49.011904 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:12:19.027414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1039eebc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054a87f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054a80d0>]}


============================== 13:12:19.029917 | 9ee6ed22-26ee-4be3-9adb-3c4b27b0498e ==============================
[0m13:12:19.029917 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:12:19.030209 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'profiles/', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select my_first_dbt_model', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:12:19.030530 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/savana/Desktop/BokksuV2/dbt-persona-project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:12:19.034276 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.043595668, "process_in_blocks": "0", "process_kernel_time": 0.105033, "process_mem_max_rss": "93421568", "process_out_blocks": "0", "process_user_time": 0.53176}
[0m13:12:19.034533 [debug] [MainThread]: Command `dbt run` failed at 13:12:19.034484 after 0.04 seconds
[0m13:12:19.034718 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1039eebc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103e568c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054a9e10>]}
[0m13:12:19.034887 [debug] [MainThread]: Flushing usage events
[0m13:12:19.388806 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:22:37.107946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCA04D120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCBF152D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCBF150F0>]}


============================== 16:22:37.114985 | 119cfc84-6d0c-4282-8e71-3f69eb51c775 ==============================
[0m16:22:37.114985 [info ] [MainThread]: Running with dbt=1.9.0
[0m16:22:37.116986 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\sansk\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:22:37.117909 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sansk\OneDrive\Desktop\dbt-persona-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:22:37.120139 [debug] [MainThread]: Command `dbt run` failed at 16:22:37.120139 after 0.13 seconds
[0m16:22:37.121172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCA04D120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCBF153C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027FCBF15390>]}
[0m16:22:37.122204 [debug] [MainThread]: Flushing usage events
[0m16:22:37.258416 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:22:50.587556 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697930D150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697B1D94E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697B1D9300>]}


============================== 16:22:50.593104 | 077455b7-6204-4dab-adb2-33f072c195fc ==============================
[0m16:22:50.593104 [info ] [MainThread]: Running with dbt=1.9.0
[0m16:22:50.594118 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\sansk\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select sanskriti_first_dbt_model', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:22:50.595119 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sansk\OneDrive\Desktop\dbt-persona-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:22:50.596120 [debug] [MainThread]: Command `dbt run` failed at 16:22:50.596120 after 0.11 seconds
[0m16:22:50.597134 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697930D150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697B1D95D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697B1D95A0>]}
[0m16:22:50.597134 [debug] [MainThread]: Flushing usage events
[0m16:22:50.724925 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:32:38.438004 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADAA6D090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADC935240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADC935060>]}


============================== 15:32:38.449135 | 61d79839-5e8d-41e5-830c-74cb1fb773da ==============================
[0m15:32:38.449135 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:32:38.451132 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\sansk\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m15:32:38.453156 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sansk\OneDrive\Desktop\dbt-persona-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:32:38.457158 [debug] [MainThread]: Command `dbt run` failed at 15:32:38.457158 after 0.24 seconds
[0m15:32:38.458154 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADAA6D090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADC935330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ADC935300>]}
[0m15:32:38.459158 [debug] [MainThread]: Flushing usage events
[0m15:32:38.617785 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:33:42.800826 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CA8CD0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CC795450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CC795270>]}


============================== 15:33:42.816365 | 13f30f15-16c9-4827-9c46-b278edf7ac01 ==============================
[0m15:33:42.816365 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:33:42.821475 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\sansk\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:33:42.824475 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sansk\OneDrive\Desktop\dbt-persona-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:33:42.830984 [debug] [MainThread]: Command `dbt run` failed at 15:33:42.829973 after 0.49 seconds
[0m15:33:42.833467 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CA8CD0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CC795540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000217CC795510>]}
[0m15:33:42.835487 [debug] [MainThread]: Flushing usage events
[0m15:33:43.005898 [debug] [MainThread]: An error was encountered while trying to flush usage events
